# NumPy-快速处理数据

NumPy中使用ndarray对象表示数组，NumPy所有的函数都是围绕ndarray对象进行处理的

In [1]:
import numpy as np

可以通过给array()函数传递Python的序列对象来创建数组，如果传递的是多层嵌套的序列，将创建多维数组

In [3]:
a=np.array([1,2,3,4])
b=np.array((5,6,7,8))
c=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

In [8]:
print(a)
print(b)
print(c)

[1 2 3 4]
[5 6 7 8]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


数组的形状可以通过其shape属性获得，它是一个描述数组各个轴的长度的元组（tuple）。可以通过修改shape属性，改变数组每个轴的长度。当设置某个轴的长度为-1时，将自动计算此轴的长度。

In [4]:
print(c.shape)
print(c)
c.shape=2,-1
print(c.shape)
print(c)

(3, 4)
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
(2, 6)
[[ 1  2  3  4  4  5]
 [ 6  7  7  8  9 10]]


使用数组的reshape()方法，可以创建指定形状的新数组，而原数组的形状保持不变。

In [5]:
d=a.reshape(2,2)
print(a)
print(d)

[ 1 20  3  4]
[[ 1 20]
 [ 3  4]]


数组a和d其实共享数据存储空间。

In [6]:
a[1]=100
print(a)
print(d)

[  1 100   3   4]
[[  1 100]
 [  3   4]]
