In [35]:
from numpy import random as nr
import numpy as np 

In [36]:
a=nr.randint(0,10,(10,10))
a

array([[6, 4, 7, 2, 4, 0, 7, 7, 2, 7],
       [8, 6, 6, 4, 0, 3, 7, 2, 4, 5],
       [0, 7, 8, 8, 5, 4, 1, 0, 0, 3],
       [7, 5, 9, 8, 7, 4, 0, 0, 5, 7],
       [9, 2, 7, 0, 9, 2, 7, 8, 4, 4],
       [3, 8, 8, 1, 0, 5, 2, 5, 4, 7],
       [0, 7, 0, 0, 7, 7, 5, 6, 7, 0],
       [1, 5, 4, 2, 6, 3, 5, 7, 5, 2],
       [2, 1, 5, 8, 5, 4, 9, 7, 9, 9],
       [6, 4, 9, 8, 7, 8, 7, 7, 0, 1]])

In [41]:
indices=nr.choice(range(10),5)
indices

array([6, 7, 1, 3, 5])

In [34]:
batch_indices=a[indices,:]
batch_indices

array([[0, 2, 9, 8, 0, 9, 0, 2, 0, 1],
       [4, 1, 5, 6, 0, 8, 0, 9, 3, 1],
       [3, 1, 5, 5, 6, 1, 8, 2, 9, 4],
       [8, 6, 1, 9, 2, 0, 4, 8, 5, 6],
       [3, 1, 5, 5, 6, 1, 8, 2, 9, 4]])